Conda packaging
neutrons/finddata pull request #21
Opened 2024-07-23 14:14 UTC by ktactac-ornl

# Short description of the changes:

Modernizes the finddata package

# Long description of the changes:

Migrate from setup.py to pyproject.toml
Updates the RPM build process

# Check list for the pull request
- [ ] I have read the [CONTRIBUTING]
- [ ] I have read the [CODE_OF_CONDUCT]
- [ ] I have added tests for my changes
- [ ] I have updated the documentation accordingly

# Check list for the reviewer
- [ ] I have read the [CONTRIBUTING]
- [ ] I have verified the proposed changes
- [ ] best software practices
    + [ ] all internal functions have an underbar, as is python standard
    + [ ] clearly named variables (better to be verbose in variable names)
    + [ ] code comments explaining the intent of code blocks
- [ ] All the tests are passing
- [ ] The documentation is up to date
- [ ] code comments added when explaining intent

# Manual test for the reviewer

# References

[4859: [finddata] Create conda package](https://ornlrse.clm.ibmcloud.com/ccm/resource/itemName/com.ibm.team.workitem.WorkItem/4859)

2024-07-23 14:25 UTC, peterfpeterson commented on pyproject.toml
>  line-length = 119
pre-commit is configured to use `ruff-format` so this should be migrated to configure that

2024-07-23 15:08 UTC, peterfpeterson commented on scripts/__init__.py
> +#!/usr/bin/env python
This is not a script. An empty file is more appropriate.

2024-07-23 15:37 UTC, peterfpeterson commented on environment.yml
> +  - conda-build < 4
Why is conda-build pinned?

2024-07-23 15:51 UTC, peterfpeterson commented on environment.yml
> +  - versioningit
You need to add toml to this file

2024-07-23 15:53 UTC, peterfpeterson commented on pyproject.toml
> +#[tool.versioningit.vcs]
Currently versioningit is unconfigured and broken. You can test this by running `versioningit .` In the root directory of the repository.

2024-07-23 15:54 UTC, ktactac-ornl commented on scripts/__init__.py
> +#!/usr/bin/env python
Caused an error if empty, I think because it's in the `scripts/` directory instead of `src/`

2024-07-23 15:55 UTC, ktactac-ornl commented on environment.yml
> +  - conda-build < 4
I think it was required for the github workflow action.
The same is true for [pystog](https://github.com/neutrons/pystog/blob/master/environment.yml)

2024-07-23 15:57 UTC, ktactac-ornl commented on environment.yml
> +  - versioningit
added

2024-07-29 17:59 UTC, peterfpeterson requested changes
The conda package appears to be good (I haven't installed it yet) but there is still something not quite right with the wheel. Unfortunately, we need the weel working to so people can pip install by repo url.

2024-07-30 15:12 UTC, ktactac-ornl commented on .github/workflows/package.yml
> +      - name: install additional dependencies
Done

2024-07-30 15:12 UTC, ktactac-ornl commented on .github/workflows/package.yml
> +      - name: build conda package
Done

2024-08-02 16:50 UTC, jmborr commented on finddata.spec
> +Version: 0.10.0
Is this _automatically_ updated when one creates a tag in branch `qa` or  `main`?

2024-08-02 16:50 UTC, jmborr commented on .github/workflows/package.yml
> +          VERSION=$(versioningit ../) conda mambabuild --output-folder . .
```suggestion
          VERSION=$(versioningit ../) conda mambabuild -c conda-forge --output-folder . .
```

2024-08-02 16:50 UTC, jmborr commented on conda.recipe/meta.yaml
> +    - versioningit
```suggestion
    - versioningit
    - setuptools
    - wheel
```
We  had to include this in drtsans' conda recipe, and it's now in the python_project_template repo.

2024-08-02 16:50 UTC, jmborr commented on conda.recipe/meta.yaml
> +    - urllib3
```suggestion
    - urllib3
    - plotly
```

2024-08-02 16:50 UTC, jmborr commented on environment.yml
> +  - urllib3
```suggestion
  - urllib3
  - plotly
```

2024-08-02 16:50 UTC, jmborr commented on pyproject.toml
> +  "urllib3",
```suggestion
  "urllib3",
  "plotly"
```

2024-08-03 15:31 UTC, peterfpeterson commented on pyproject.toml
> +  "urllib3",
If I add plotly here then the patchfile will have to remove it. This gets converted to dependencies in the rpm and no plotly rpm exists. If I wanted to spend a bunch more effort, I would split finddata into a command line package and a full package so the dependencies could be managed better.

2024-08-03 15:58 UTC, jmborr commented on pyproject.toml
> +  "urllib3",
That's OK, then. What a pity there's no RPM.

2024-08-05 17:43 UTC, peterfpeterson approved these changes

2024-08-05 18:32 UTC, jmborr approved these changes
looks :ok_hand:

2024-08-05 19:26 UTC, merged